#!/bin/sh
# WorkTime Logger — macOS launcher layer installer.
#
# Installs:
#   - 5 tiny Spotlight-searchable .app bundles in ~/Applications (Start,
#     Stop, Dashboard, Weekly Report, Monthly Report), each just a launcher
#     shell script that execs bin/worktime with the right subcommand.
#   - a 'worktime' symlink in ~/.local/bin, for terminal use.
#   - prints the Aerospace keybinding lines to paste into your own
#     aerospace.toml.
#
# It NEVER edits your Aerospace config (or any other window manager
# config) automatically — you paste the printed lines in yourself.
#
# Usage:
#   install.sh              install (safe to run more than once)
#   install.sh --uninstall  remove what this script installed
#   install.sh -h|--help    show this help
set -eu

usage() {
    cat <<'EOF'
Usage: install.sh [--uninstall|-h|--help]

Install WorkTime Logger's macOS launcher layer:
  - 5 Spotlight-searchable apps in ~/Applications
  - a 'worktime' symlink in ~/.local/bin
  - prints Aerospace keybinding lines for you to paste in manually

Options:
  --uninstall   remove the apps and symlink installed by this script
  -h, --help    show this help and exit
EOF
}

case "${1:-}" in
    "")
        mode=install
        ;;
    --uninstall)
        mode=uninstall
        ;;
    -h|--help)
        usage
        exit 0
        ;;
    *)
        usage >&2
        exit 2
        ;;
esac

if [ "$(uname -s)" != "Darwin" ]; then
    echo "worktime install: macOS only — on Linux use platform/linux/install.sh" >&2
    exit 1
fi

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd -P)
REPO=$(cd "$SCRIPT_DIR/../.." && pwd -P)
WT="$REPO/bin/worktime"
TEMPLATE="$SCRIPT_DIR/aerospace-bindings.toml"

case "$REPO" in
    *'"'*|*'$'*|*'`'*|*'\'*)
        echo "worktime install: path contains unsupported characters: $REPO" >&2
        exit 1
        ;;
esac

APPS_DIR="$HOME/Applications"

should_register() {
    case "${WORKTIME_INSTALL_NO_REGISTER:-}" in
        1|true|yes) return 1 ;;
        *) return 0 ;;
    esac
}

# make_app NAME ID ARGS...
make_app() {
    name="$1"
    id="$2"
    shift 2
    args="$*"
    dir="$APPS_DIR/$name.app"

    if [ -e "$dir" ]; then
        if [ -f "$dir/Contents/Info.plist" ] && grep -F -q "local.worktime." "$dir/Contents/Info.plist" 2>/dev/null; then
            : # ours — recreate below to keep it in sync
        else
            echo "Skipping $name.app: exists and was not created by WorkTime" >&2
            return 0
        fi
    fi

    rm -rf "$dir"
    mkdir -p "$dir/Contents/MacOS"

    cat > "$dir/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleExecutable</key><string>worktime-launcher</string>
  <key>CFBundleIdentifier</key><string>local.worktime.$id</string>
  <key>CFBundleName</key><string>$name</string>
  <key>CFBundleDisplayName</key><string>$name</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>LSUIElement</key><true/>
</dict>
</plist>
EOF

    cat > "$dir/Contents/MacOS/worktime-launcher" <<EOF
#!/bin/sh
# Generated by platform/macos/install.sh. Re-run it after moving the repo.
exec "$WT" $args
EOF
    chmod 755 "$dir/Contents/MacOS/worktime-launcher"

    # Newer macOS Spotlight/SystemIntents refuses to open unsigned bundles
    # (fails with "does not have permission to open (null)"). Ad-hoc signing
    # is purely local (no Apple account, no network) and fixes this. It is
    # not gated behind WORKTIME_INSTALL_NO_REGISTER since it never talks to
    # any external service.
    if command -v codesign >/dev/null 2>&1; then
        if ! codesign --force --sign - "$dir" >/dev/null 2>&1; then
            echo "Warning: could not sign $name.app (Spotlight may refuse to open it)" >&2
        fi
    else
        echo "Warning: could not sign $name.app (Spotlight may refuse to open it)" >&2
    fi

    if should_register; then
        /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$dir" >/dev/null 2>&1 || true
        mdimport "$dir" >/dev/null 2>&1 || true
    fi

    echo "$dir"
}

# remove_app NAME
remove_app() {
    name="$1"
    dir="$APPS_DIR/$name.app"
    if [ -d "$dir" ]; then
        if [ -f "$dir/Contents/Info.plist" ] && grep -F -q "local.worktime." "$dir/Contents/Info.plist" 2>/dev/null; then
            rm -rf "$dir"
            echo "Removed $name.app"
        else
            echo "Skipping $name.app: exists and was not created by WorkTime" >&2
        fi
    fi
}

do_install() {
    if ! "$WT" --version >/dev/null 2>&1; then
        echo "worktime install: bin/worktime could not find Python >= 3.11 (set WORKTIME_PYTHON)" >&2
        exit 1
    fi

    mkdir -p "$APPS_DIR"

    echo "Creating Spotlight launchers in $APPS_DIR:"
    make_app "WorkTime Start" start start
    make_app "WorkTime Stop" stop stop
    make_app "WorkTime Dashboard" dashboard dashboard
    make_app "WorkTime Weekly Report" report-week report week
    make_app "WorkTime Monthly Report" report-month report month

    mkdir -p "$HOME/.local/bin"
    L="$HOME/.local/bin/worktime"
    if [ -e "$L" ] && [ ! -L "$L" ]; then
        echo "Skipping ~/.local/bin/worktime: a file already exists there" >&2
    else
        ln -sfn "$WT" "$L"
        echo "Symlinked $L -> $WT"
    fi

    case ":$PATH:" in
        *":$HOME/.local/bin:"*)
            ;;
        *)
            echo ""
            echo "Add this to ~/.zshrc to use 'worktime' in the terminal:"
            printf '  export PATH="%s/.local/bin:$PATH"\n' "$HOME"
            ;;
    esac

    echo ""
    echo "Aerospace: paste these lines under [mode.main.binding] in your aerospace.toml, then reload (alt-shift-c):"
    sed -e '/^#/d' -e '/^[[:space:]]*$/d' "$TEMPLATE" | sed "s|@WORKTIME@|$WT|g"

    for key in t x d r; do
        bind="alt-shift-$key"
        match=""
        matchfile=""
        for f in "$HOME/.config/aerospace/aerospace.toml" "$HOME/.aerospace.toml"; do
            if [ -f "$f" ]; then
                line=$(grep -E "^[[:space:]]*$bind[[:space:]]*=" "$f" 2>/dev/null | head -n 1 || true)
                if [ -n "$line" ]; then
                    match="$line"
                    matchfile="$f"
                    break
                fi
            fi
        done
        if [ -n "$match" ]; then
            case "$match" in
                *worktime*)
                    echo "$bind: already configured"
                    ;;
                *)
                    echo "Warning: $bind is already bound in $matchfile"
                    ;;
            esac
        fi
    done

    echo ""
    echo "Done. Installed:"
    echo "  $APPS_DIR/WorkTime Start.app"
    echo "  $APPS_DIR/WorkTime Stop.app"
    echo "  $APPS_DIR/WorkTime Dashboard.app"
    echo "  $APPS_DIR/WorkTime Weekly Report.app"
    echo "  $APPS_DIR/WorkTime Monthly Report.app"
    echo "  $L"
    echo ""
    echo "Type 'worktime' in Spotlight to find the launchers."
    echo "First notification: if nothing appears, allow notifications for 'Script Editor' in System Settings -> Notifications."
}

do_uninstall() {
    remove_app "WorkTime Start"
    remove_app "WorkTime Stop"
    remove_app "WorkTime Dashboard"
    remove_app "WorkTime Weekly Report"
    remove_app "WorkTime Monthly Report"

    L="$HOME/.local/bin/worktime"
    if [ -L "$L" ]; then
        target=$(readlink "$L")
        if [ "$target" = "$WT" ]; then
            rm -f "$L"
            echo "Removed $L"
        fi
    fi

    echo "Remove the WorkTime lines (alt-shift-t/x/d/r) from your aerospace.toml manually."
}

if [ "$mode" = "install" ]; then
    do_install
else
    do_uninstall
fi
